### ISSUE TITLE
can't find non-host targets?

### ISSUE THREAD

**Issue by rbelew** [tox-dev/pipdeptree#160]
pipdeptree --version = 2.2.0

I'm trying to make use of this very helpful utility, to
compare/contrast various "non-host" environments i've built using
conda.  i have this simple script:

		condaBase="/fullPathTo/miniconda3/"
		envs="scipy sp2 py39 cvsim"
		for e in scipy sp2 py39 cvsim; do
		# graphviz functionality is not supported when querying non-host python
		# pipdeptree --graph-output png --python $condaBase$e > $e-dep.png
		pipdeptree --json-tree --python $condaBase$e/bin/python > $e-dep.json
		echo $e done
		done

but for some reason pipdeptree doesn't find the python path:

		Traceback (most recent call last):
		File "/Library/Frameworks/Python.framework/Versions/3.10/bin/pipdeptree", line 8, in <module>
		sys.exit(main())
		File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pipdeptree.py", line 833, in main
		result = handle_non_host_target(args)
		File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pipdeptree.py", line 825, in handle_non_host_target
		return subprocess.call(cmd, cwd=cwd)
		File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 345, in call
		with Popen(*popenargs, **kwargs) as p:
		File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 966, in __init__
		self._execute_child(args, executable, preexec_fn, close_fds,
		File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1842, in _execute_child
		raise child_exception_type(errno_num, err_msg, err_filename)
		FileNotFoundError: [Errno 2] No such file or directory: '/fullPathTo/miniconda3/scipy/bin/python'

This path *does* exist, i can execute the python using this path, ... Any ideas what's up?

**Comment by naiquevin** [comment]
The path printed in the stacktrace looks like a relative path `.../miniconda3/scipy/bin/python`. May be it's because pipdeptree is trying to resolve the relative path from its own location. Can you please try providing absolute path of the conda environment?

**Comment by rbelew** [comment]
thanks for your help@naiquevin!  `pipdeptree` is a very handy tool, thanks for your work!

And apologies, my use of the `...` ellipsis was just to hide details (user, machine name, etc.).  the script and the trace both do give absolute paths.

**Comment by naiquevin** [comment]
That's strange. I am not familiar with conda as such but could it be a permissions issue? Does the user running the script has permissions to execute `/fullPathTo/miniconda3/scipy/bin/python`?

**Comment by gaborbernat** [comment]
Closing as no further information was provided.
