### ISSUE TITLE
AttributeError messages generating mermaid output for reverse dependencies

### ISSUE THREAD

**Issue by ajkerrigan** [tox-dev/pipdeptree#207]
I was using a command like this (on pipdeptree version `2.5.2`):

```console
❯ pipdeptree --python (py -c 'import sys; print(sys.executable)') -p packaging -r --mermaid
```

And getting these errors:

```console
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/tmpyyjztxs5/pipdeptree/__main__.py", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/tmp/tmpyyjztxs5/pipdeptree/__init__.py", line 980, in main
    print(render_mermaid(tree))
          ^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmpyyjztxs5/pipdeptree/__init__.py", line 609, in render_mermaid
    pkg_label = f"{pkg.project_name}\\n{pkg.version}"
                                        ^^^^^^^^^^^
  File "/tmp/tmpyyjztxs5/pipdeptree/__init__.py", line 121, in __getattr__
    return getattr(self._obj, key)
           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Requirement' object has no attribute 'version'
```

```console
Traceback (most recent call last):                                                                                                                                
  File "<frozen runpy>", line 198, in _run_module_as_main                                                                                                         
  File "<frozen runpy>", line 88, in _run_code                                                                                                                    
  File "/tmp/tmplc94do0z/pipdeptree/__main__.py", line 6, in <module>                                                                                             
    sys.exit(main())                                                                                                                                              
             ^^^^^^                                                                                                                                               
  File "/tmp/tmplc94do0z/pipdeptree/__init__.py", line 980, in main                                                                                               
    print(render_mermaid(tree))                                                                                                                                   
          ^^^^^^^^^^^^^^^^^^^^                                                                                                                                    
  File "/tmp/tmplc94do0z/pipdeptree/__init__.py", line 615, in render_mermaid                                                                                     
    if dep.is_missing:                                                                                                                                            
       ^^^^^^^^^^^^^^                                                                                                                                             
  File "/tmp/tmplc94do0z/pipdeptree/__init__.py", line 121, in __getattr__                                                                                        
    return getattr(self._obj, key)                                                                                                                                
           ^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                
  File "/home/aj/.pyenv/versions/c7n-dev/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2816, in __getattr__                           
    return getattr(self._provider, attr)                                                                                                                          
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                          
AttributeError: 'PathMetadata' object has no attribute 'is_missing'
```

I worked around those issues locally (PR incoming in case it's useful), but just wanted to log it in case someone else runs into the same thing.

I love pipdeptree so much, and the mermaid output is a sweet addition. Thank you to the folks making it possible ❤️

**Comment by ajkerrigan** [comment]
For what it's worth, [this](https://github.com/cloud-custodian/cloud-custodian/issues/8394#issuecomment-1474079743) shows output that includes these tweaks.
