### ISSUE TITLE
2.10.0: Error cmd pipdeptree --graph-output svc

### ISSUE THREAD

**Issue by rsrpsinr** [tox-dev/pipdeptree#270]
Was ok <2.10 with python 3.10

command:
`pipdeptree --graph-output svg`

```
Traceback (most recent call last):
  File "/tmp/venv_py3.10/bin/pipdeptree", line 8, in <module>
    sys.exit(main())
  File "/tmp/venv_py3.10/lib64/python3.10/site-packages/pipdeptree/__main__.py", line 36, in main
    render(args, tree)
  File "/tmp/venv_py3.10/lib64/python3.10/site-packages/pipdeptree/_render/__init__.py", line 24, in render
    assert options.graph_output is not None  # noqa: S101
AttributeError: 'Namespace' object has no attribute 'graph_output'
```

**Comment by rsrpsinr** [comment]
Apology. Just realized this is same as #269
