### ISSUE TITLE
Using pipdeptree in tox with tox-uv gives ModuleNotFoundError for pip

### ISSUE THREAD

**Issue by reinout** [tox-dev/pipdeptree#331]
A bit of a corner case. I'm experimenting with `tox-uv` to use uv within tox.
A bit cleaned up ([see full one](https://github.com/nens/nens-meta/blob/main/tox.ini):

```
[testenv:dependencies-graph]
description = Generate a graph out of the dependencies of the package
skip_install = false
deps =
    pipdeptree>=2.5.1
    graphviz  # optional dependency of pipdeptree
commands =
    - pipdeptree --packages nens-meta --mermaid
```

When running the tox-with-uv version, I get this traceback:

```
Traceback (most recent call last):
  File "/Users/reinout/nens/nens-meta/.tox/dependencies-graph/.venv/bin/pipdeptree", line 5, in <module>
    from pipdeptree.__main__ import main
  File "/Users/reinout/nens/nens-meta/.tox/dependencies-graph/.venv/lib/python3.12/site-packages/pipdeptree/__main__.py", line 10, in <module>
    from pipdeptree._models import PackageDAG
  File "/Users/reinout/nens/nens-meta/.tox/dependencies-graph/.venv/lib/python3.12/site-packages/pipdeptree/_models/__init__.py", line 3, in <module>
    from .dag import PackageDAG, ReversedPackageDAG
  File "/Users/reinout/nens/nens-meta/.tox/dependencies-graph/.venv/lib/python3.12/site-packages/pipdeptree/_models/dag.py", line 12, in <module>
    from .package import DistPackage, ReqPackage, pep503_normalize
  File "/Users/reinout/nens/nens-meta/.tox/dependencies-graph/.venv/lib/python3.12/site-packages/pipdeptree/_models/package.py", line 10, in <module>
    from pip._vendor.pkg_resources import Requirement  # noqa: PLC2701
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pip'
```

When I investigate the virtualenv created by tox-uv, the `pipdeptree-2.16.1.dist-info/METADATA` contains the proper `Requires-Dist: pip>=23.3.1; extra == 'test'`, so pipdeptree's dependency list is fine. **My guess** is that `uv` doesn't install pip itself as it mimicks pip. It only doesn't need to mimick "old stuff" like the `_vendor.pkg_resources`. Which is probably OK. There's a PR here to move away from pkg_resources (#175).

**Workaround**: if I add `pip` as an explicit dependency in this tox environment's `deps =` list it *does* work.

I'm not sure if it is an issue here (which probably means #175) or with tox-uv (or uv), ignoring a "pip" dependency.

**Comment by gaborbernat** [comment]
That's expected 😊 after all, the name of this project is pipdeptree, so is expecting to have pip in the env. You can achieve via tox-uv that by setting `uv_seed = true` in your tox config.

**Comment by reinout** [comment]
The `uv_seed = true` indeed works perfectly.
