### ISSUE TITLE
Depend on pip

### ISSUE THREAD

**Issue by pawamoy** [tox-dev/pipdeptree#335]
pipdeptree depends on pip:

```python
Traceback (most recent call last):
  File "/media/data/dev/markdown-exec/.venv/bin/pipdeptree", line 5, in <module>
    from pipdeptree.__main__ import main
  File "/media/data/dev/markdown-exec/.venv/lib/python3.11/site-packages/pipdeptree/__main__.py", line 10, in <module>
    from pipdeptree._models import PackageDAG
  File "/media/data/dev/markdown-exec/.venv/lib/python3.11/site-packages/pipdeptree/_models/__init__.py", line 3, in <module>
    from .dag import PackageDAG, ReversedPackageDAG
  File "/media/data/dev/markdown-exec/.venv/lib/python3.11/site-packages/pipdeptree/_models/dag.py", line 12, in <module>
    from .package import DistPackage, ReqPackage, pep503_normalize
  File "/media/data/dev/markdown-exec/.venv/lib/python3.11/site-packages/pipdeptree/_models/package.py", line 10, in <module>
    from pip._vendor.pkg_resources import Requirement  # noqa: PLC2701
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pip'
```

...so I would suggest to add `pip` as a dependency, in pyproject.toml. It is less and less common to have pip automatically installed in virtualenvs, so this shouldn't be expected anymore that pip is always installed alongside a package :slightly_smiling_face: Happy to send a PR!

Related: https://github.com/tox-dev/pipdeptree/issues/331

**Comment by gaborbernat** [comment]
cc @kemzeb

**Comment by kemzeb** [comment]
Seems reasonable enough; feel free to open a PR!

**Comment by austinpray-mixpanel** [comment]
Opened a PR to lax up the pip version range to support use case of using pipdeptree to revive projects stuck on ancient versions of pip 👍 https://github.com/tox-dev/pipdeptree/pull/340
