### ISSUE TITLE
Error in `canonicalize_name` with `None` metadata name

### ISSUE THREAD

**Issue by fmigneault** [tox-dev/pipdeptree#370]
### What pipdeptree version are you using?

2.21.0

### Are you running pipdeptree in a virtual environment?

Yes

### Describe the problem

Install `docker-py` (https://github.com/docker/docker-py) and `pipdeptree`. 
```shell
pip install docker pipdeptree
```

Then, try to display `docker` requirements: 

```shell
pipdeptree  -p 'docker' --python 'auto'
Traceback (most recent call last):
  File "/home/francis/dev/miniconda/bin/pipdeptree", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/francis/dev/miniconda/lib/python3.11/site-packages/pipdeptree/__main__.py", line 31, in main
    pkgs = get_installed_distributions(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/francis/dev/miniconda/lib/python3.11/site-packages/pipdeptree/_discovery.py", line 58, in get_installed_distributions
    normalized_name = canonicalize_name(dist.metadata["Name"])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/francis/dev/miniconda/lib/python3.11/site-packages/packaging/utils.py", line 47, in canonicalize_name
    value = _canonicalize_regex.sub("-", name).lower()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
```

Although the package is installed and identified properly by `pip`: 
```shell
pip show docker
Name: docker
Version: 6.1.3
Summary: A Python library for the Docker Engine API.
Home-page: https://github.com/docker/docker-py
Author: 
Author-email: 
License: Apache License 2.0
Location: /home/francis/dev/miniconda/envs/weaver-py310/lib/python3.10/site-packages
Requires: packaging, requests, urllib3, websocket-client
Required-by: weaver
```

**Comment by kemzeb** [comment]
Hmm I have not been able to reproduce this. From what I can see in your command line used + output, it looks like:
- You're running in a conda environment with Python v3.11
- Installed `pipdeptree` in the "base" conda environment (since I see the path `.../dev/miniconda/bin/pipdeptree`)
- Installed `docker` and another `pipdeptree` in the "weaver-py310" conda env, which is using Python v3.10
- Ran `pipdeptree  -p 'docker' --python 'auto'` in the "weaver-py310" env

After trying to recreate this environment, I haven't been able to reproduce. The steps I used:
```bash
$ bash Miniconda3-latest-Linux-aarch64.sh
. . . # installed and started new shell session
(base) $ conda --version
conda 24.4.0
(base) $ python --version
Python 3.12.3
(base) $ pip install pipdeptree
. . .
(base) $ pipdeptree --version
2.21.0
(base) $ conda create -n py310 python=3.10
(py310) $ python --version
Python 3.10.14
(py310) $ pip install docker pipdeptree
. . .
(py310) $ pipdeptree  -p 'docker' --python 'auto'
docker==7.0.0
├── packaging [required: >=14.0, installed: 24.0]
├── requests [required: >=2.26.0, installed: 2.32.2]
│   ├── certifi [required: >=2017.4.17, installed: 2024.2.2]
│   ├── charset-normalizer [required: >=2,<4, installed: 3.3.2]
│   ├── idna [required: >=2.5,<4, installed: 3.7]
│   └── urllib3 [required: >=1.21.1,<3, installed: 2.2.1]
└── urllib3 [required: >=1.26.0, installed: 2.2.1]
(py310) $ 
```

I also created an environment where the Python versions match and no problems either.

Also, from your output it looks like `dist.metadata['Name']` is returning `None`. This is weird as distribution packages [must](https://packaging.python.org/en/latest/specifications/core-metadata/) have the `Name` field.

What is the output when running the interactive interpreter in this environment with the following statements:
```python
>>> from importlib.metadata import distribution
>>> d = distribution('docker')
>>> d.metadata['Name']
'docker'
>>>
```

Also, do you have any other packages that may have been in your environment or is this a newly-created env with only `docker` and `pipdeptree`?

**Comment by kemzeb** [comment]
After rebuilding my dev container and installing your packages like the following:

(Note I also had to do `conda install gdal` or else the installation below would fail)

```bash
pip install -r https://raw.githubusercontent.com/crim-ca/weaver/master/requirements.txt -r https://raw.githubusercontent.com/crim-ca/weaver/master/requirements-dev.txt -r https://raw.githubusercontent.com/crim-ca/weaver/master/requirements-sys.txt -r https://raw.githubusercontent.com/crim-ca/weaver/master/requirements-doc.txt
```
... and also installing `pipdeptree` in the base environment (which now runs Python v3.11) and `docker` in my "py310" environment, I still haven't been able to reproduce:
```bash
(py310) $ /home/vscode/miniconda3/bin/pipdeptree  -p 'docker' --python 'auto'
docker==7.1.0
├── requests [required: >=2.26.0, installed: 2.31.0]
│   ├── certifi [required: >=2017.4.17, installed: 2024.2.2]
│   ├── charset-normalizer [required: >=2,<4, installed: 3.3.2]
│   ├── idna [required: >=2.5,<4, installed: 3.7]
│   └── urllib3 [required: >=1.21.1,<3, installed: 2.2.1]
└── urllib3 [required: >=1.26.0, installed: 2.2.1]
```

I should note that when you do `-p docker`, we will still scan your entire environment and afterwards just filter it looking for a package name "docker". Because of this, my guess so far is that you may have some invalid `METADATA` file in your environment. I don't think it is `docker` since `pip show` was able to read the `METADATA` file properly. We use `importlib.metadata.distributions()` internally, and I tested to see if it will take an **empty** `METADATA` file. Turns out it does:
```python
(base) $ python
Python 3.10.14 (main, May  6 2024, 19:36:58) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from importlib.metadata import distributions
>>> dists = list(distributions())
>>> bad_dists = [d for d in dists if not d.metadata.get('Name')]
>>> assert len(bad_dists) > 0
>>> fake = bad_dists[0]
>>> fake._path
PosixPath('/home/vscode/miniconda3/envs/py310/lib/python3.10/site-packages/fake-1.2.3.dist-info')
>>> 
```

When you get the time, may you run these statements in an interactive interpreter in your conda environment?

**Comment by fmigneault** [comment]
I am still not sure where the empty distribution is coming from, but I don't think it is specifically related to `docker`. I think the code simply encounters the `None` while looping the distributions while looking for it and crashes. This can probably be avoided by simply filtering out `None` beforehand. 

Here's my investigation output:

```shell
❯ which python
/home/francis/dev/conda/envs/weaver/bin/python
❯ which pipdeptree
/home/francis/dev/miniconda/bin/pipdeptree
❯ python
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from importlib.metadata import distributions
>>> import sys
>>> sys.prefix 
'/home/francis/dev/conda/envs/weaver'
>>> sys.path 
['', '/home/francis/dev/conda/envs/weaver/lib/python310.zip', '/home/francis/dev/conda/envs/weaver/lib/python3.10', '/home/francis/dev/conda/envs/weaver/lib/python3.10/lib-dynload', '/home/francis/dev/conda/envs/weaver/lib/python3.10/site-packages', '/home/francis/dev/weaver']
>>> paths=sys.path 
>>> dist_names = sorted([dist.metadata["Name"] for dist in distributions(path=paths)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '<' not supported between instances of 'NoneType' and 'str'
>>> dist_names = [dist.metadata["Name"] for dist in distributions(path=paths)]
>>> dist_names
['safety-schemas', 'PasteDeploy', 'PasteDeploy', 'requests-magpie', 'types-s3transfer', 'untokenize', 'contextlib2', 'sphinxcontrib-qthelp', 'sphinxcontrib-qthelp', 'pylint-quotes', 'zope.deprecation', 'zope.deprecation', 'PySocks', 'requests-file', 'future', 'pytest-shutil', 'botocore', 'six', 'humanfriendly', 'termcolor', 'Jinja2', 'Jinja2', 'WebOb', 'tomli', 'sphinxcontrib-applehelp', 'sphinxcontrib-applehelp', 'requests', 'soupsieve', 'path.py', 'argcomplete', 'py', 'coloredlogs', 'cornice-swagger', 'attrs', 'amqp', 'sphinxcontrib-serializinghtml', 'sphinxcontrib-serializinghtml', 'Beaker', 'Beaker', 'Sphinx', 'Sphinx', None, 'urllib3', 'Werkzeug', 'lxml', 'doc8', 'pycodestyle', 'pytest-httpserver', 'pylint-per-file-ignores', 'asciitree', 'pylint', 'pymongo', 'mock', 'moto', 'cligj', 'charset-normalizer', 'ruamel.yaml.clib', 'wcwidth', 'mistune', 'sphinxcontrib-jsmath', 'zope.interface', 'zope.interface', 'mypy-extensions', 'hupper', 'hupper', 's3transfer', 'MarkupSafe', 'cwl-upgrader', 'idna', 'psutil', 'docker', 'docutils', 'docutils', 'types-awscrt', 'plaster', 'plaster', 'Pygments', 'Pygments', 'path', 'fasteners', 'marshmallow', 'pytz', 'pytz', 'python-dateutil', 'celery', 'alembic', 'alabaster', 'alabaster', 'smmap', 'pluggy', 'gunicorn', 'Mako', 'Mako', 'iso8601', 'pyramid-beaker', 'pytest-fixture-config', 'packaging', 'packaging', 'click-didyoumean', 'mdurl', 'GitPython', 'python-box', 'billiard', 'translationstring', 'translationstring', 'setuptools', 'setuptools', 'setuptools', 'pywps', 'Babel', 'Babel', 'parameterized', 'prompt-toolkit', 'esgf-compute-api', 'Authlib', 'annotated-types', 'pyramid', 'pyramid', 'PyYAML', 'anyascii', 'tifffile', 'astroid', 'types-html5lib', 'pydantic_core', 'pip', 'pip', 'WSGIProxy', 'OWSLib', 'botocore-stubs', 'pycparser', 'rdflib', 'ruamel.yaml', 'sphinx-paramlinks', 'coverage', 'pyramid-rewrite', 'pyramid-mako', 'defusedxml', 'jmespath', 'kombu', 'iniconfig', 'pydantic', 'humanize', 'stopit', 'cryptography', 'websocket-client', 'cffi', 'importlib-resources', 'prov', 'jsonschema', 'sphinxcontrib-htmlhelp', 'sphinxcontrib-htmlhelp', 'CacheControl', 'restructuredtext-lint', 'oauthlib', 'colander', 'pytest', 'colorama', 'fiona', 'cwl-utils', 'Paste', 'sphinxcontrib-devhelp', 'sphinxcontrib-devhelp', 'pyramid-celery', 'cwltool', 'numcodecs', 'dparse', 'pyramid-storage', 'flake8', 'vine', 'pyflakes', 'typer', 'shapely', 'Brotli', 'mccabe', 'typing_extensions', 'stevedore', 'SQLAlchemy', 'shellingham', 'tomlkit', 'lazy-object-proxy', 'numpy', 'wrapt', 'pyproj', 'xmltodict', 'mypy-boto3-s3', 'WSGIProxy2', 'docformatter', 'imagesize', 'shellescape', 'markdown-it-py', 'boto3', 'networkx', 'click-repl', 'bandit', 'boto3-stubs', 'snowballstemmer', 'duration', 'pydocstyle', 'certifi', 'astor', 'wheel', 'WebTest', 'cornice', 'codacy-coverage', 'isodate', 'sphinx-rtd-theme', 'venusian', 'venusian', 'plaster-pastedeploy', 'plaster-pastedeploy', 'responses', 'click-plugins', 'simplejson', 'pyparsing', 'jsonschema-specifications', 'sphinx-autodoc-typehints', 'pydot', 'Pint', 'isort', 'rpds-py', 'urlmatch', 'toml', 'gitdb', 'zarr', 'pytest-server-fixtures', 'greenlet', 'types-requests', 'safety', 'pbr', 'flynt', 'geotiff', 'beautifulsoup4', 'dill', 'sphinx-autoapi', 'schema-salad', 'referencing', 'filelock', 'sphinxcontrib-jquery', 'click', 'tzdata', 'rich', 'decorator', 'msgpack', 'execnet', 'sphinxcontrib-redoc', 'retry', 'waitress', 'pytest-rerunfailures', 'sphinx-argparse', 'mypy', 'dnspython', 'json2xml', 'platformdirs', 'bump2version', 'weaver']
>>> import json
>>> print(json.dumps(dist_names, indent=2))
[
  "safety-schemas",
  "PasteDeploy",
  "PasteDeploy",
  "requests-magpie",
  "types-s3transfer",
  "untokenize",
  "contextlib2",
  "sphinxcontrib-qthelp",
  "sphinxcontrib-qthelp",
  "pylint-quotes",
  "zope.deprecation",
  "zope.deprecation",
  "PySocks",
  "requests-file",
  "future",
  "pytest-shutil",
  "botocore",
  "six",
  "humanfriendly",
  "termcolor",
  "Jinja2",
  "Jinja2",
  "WebOb",
  "tomli",
  "sphinxcontrib-applehelp",
  "sphinxcontrib-applehelp",
  "requests",
  "soupsieve",
  "path.py",
  "argcomplete",
  "py",
  "coloredlogs",
  "cornice-swagger",
  "attrs",
  "amqp",
  "sphinxcontrib-serializinghtml",
  "sphinxcontrib-serializinghtml",
  "Beaker",
  "Beaker",
  "Sphinx",
  "Sphinx",
  null,
  "urllib3",
  "Werkzeug",
  "lxml",
  "doc8",
  "pycodestyle",
  "pytest-httpserver",
  "pylint-per-file-ignores",
  "asciitree",
  "pylint",
  "pymongo",
  "mock",
  "moto",
  "cligj",
  "charset-normalizer",
  "ruamel.yaml.clib",
  "wcwidth",
  "mistune",
  "sphinxcontrib-jsmath",
  "zope.interface",
  "zope.interface",
  "mypy-extensions",
  "hupper",
  "hupper",
  "s3transfer",
  "MarkupSafe",
  "cwl-upgrader",
  "idna",
  "psutil",
  "docker",
  "docutils",
  "docutils",
  "types-awscrt",
  "plaster",
  "plaster",
  "Pygments",
  "Pygments",
  "path",
  "fasteners",
  "marshmallow",
  "pytz",
  "pytz",
  "python-dateutil",
  "celery",
  "alembic",
  "alabaster",
  "alabaster",
  "smmap",
  "pluggy",
  "gunicorn",
  "Mako",
  "Mako",
  "iso8601",
  "pyramid-beaker",
  "pytest-fixture-config",
  "packaging",
  "packaging",
  "click-didyoumean",
  "mdurl",
  "GitPython",
  "python-box",
  "billiard",
  "translationstring",
  "translationstring",
  "setuptools",
  "setuptools",
  "setuptools",
  "pywps",
  "Babel",
  "Babel",
  "parameterized",
  "prompt-toolkit",
  "esgf-compute-api",
  "Authlib",
  "annotated-types",
  "pyramid",
  "pyramid",
  "PyYAML",
  "anyascii",
  "tifffile",
  "astroid",
  "types-html5lib",
  "pydantic_core",
  "pip",
  "pip",
  "WSGIProxy",
  "OWSLib",
  "botocore-stubs",
  "pycparser",
  "rdflib",
  "ruamel.yaml",
  "sphinx-paramlinks",
  "coverage",
  "pyramid-rewrite",
  "pyramid-mako",
  "defusedxml",
  "jmespath",
  "kombu",
  "iniconfig",
  "pydantic",
  "humanize",
  "stopit",
  "cryptography",
  "websocket-client",
  "cffi",
  "importlib-resources",
  "prov",
  "jsonschema",
  "sphinxcontrib-htmlhelp",
  "sphinxcontrib-htmlhelp",
  "CacheControl",
  "restructuredtext-lint",
  "oauthlib",
  "colander",
  "pytest",
  "colorama",
  "fiona",
  "cwl-utils",
  "Paste",
  "sphinxcontrib-devhelp",
  "sphinxcontrib-devhelp",
  "pyramid-celery",
  "cwltool",
  "numcodecs",
  "dparse",
  "pyramid-storage",
  "flake8",
  "vine",
  "pyflakes",
  "typer",
  "shapely",
  "Brotli",
  "mccabe",
  "typing_extensions",
  "stevedore",
  "SQLAlchemy",
  "shellingham",
  "tomlkit",
  "lazy-object-proxy",
  "numpy",
  "wrapt",
  "pyproj",
  "xmltodict",
  "mypy-boto3-s3",
  "WSGIProxy2",
  "docformatter",
  "imagesize",
  "shellescape",
  "markdown-it-py",
  "boto3",
  "networkx",
  "click-repl",
  "bandit",
  "boto3-stubs",
  "snowballstemmer",
  "duration",
  "pydocstyle",
  "certifi",
  "astor",
  "wheel",
  "WebTest",
  "cornice",
  "codacy-coverage",
  "isodate",
  "sphinx-rtd-theme",
  "venusian",
  "venusian",
  "plaster-pastedeploy",
  "plaster-pastedeploy",
  "responses",
  "click-plugins",
  "simplejson",
  "pyparsing",
  "jsonschema-specifications",
  "sphinx-autodoc-typehints",
  "pydot",
  "Pint",
  "isort",
  "rpds-py",
  "urlmatch",
  "toml",
  "gitdb",
  "zarr",
  "pytest-server-fixtures",
  "greenlet",
  "types-requests",
  "safety",
  "pbr",
  "flynt",
  "geotiff",
  "beautifulsoup4",
  "dill",
  "sphinx-autoapi",
  "schema-salad",
  "referencing",
  "filelock",
  "sphinxcontrib-jquery",
  "click",
  "tzdata",
  "rich",
  "decorator",
  "msgpack",
  "execnet",
  "sphinxcontrib-redoc",
  "retry",
  "waitress",
  "pytest-rerunfailures",
  "sphinx-argparse",
  "mypy",
  "dnspython",
  "json2xml",
  "platformdirs",
  "bump2version",
  "weaver"
]
>>> for dist in distributions(path=paths):
...     if dist.metadata["Name"] is None:
...             break
... 
>>> dist
<importlib.metadata.PathDistribution object at 0x7ffb313f26e0>
>>> dist.
dist.at(           dist.entry_points  dist.from_name(    dist.metadata      dist.read_text(    dist.version       
dist.discover(     dist.files         dist.locate_file(  dist.name          dist.requires      
>>> dist.files  # None
>>> dist.name  # None     
>>> dist.version  # None       
>>> dict(dist.metadata)
{}
>>> 

```
